### ISSUE TITLE
Cannot access preferences after installation

### ISSUE THREAD

**Issue by makkes** [thomasklein/redmine2mite#30]
I installed the plugin on a system with these specs:

```
Environment:
  Redmine version                          2.0.3.stable
  Ruby version                             1.8.7 (x86_64-linux)
  Rails version                            3.2.6
  Environment                              production
  Database adapter                         MySQL
Redmine plugins:
  due_date_reminder                        0.3.2
  redmine2mite                             2.1.1
```

After running the migrate task I try to access "/mite" and get an internal error. The log shows this:

```
ActionView::Template::Error (No such file or directory - Asset file not found at '/var/www/redmine/public/stylesheets/plugin_assets/redmine2mite/stylesheets/mite_preferences.css'):
    1: <% content_for :header_tags do %>
    2:  <%= stylesheet_link_tag 'mite_preferences', :plugin => 'redmine2mite', :cache => true %>
    3: <% end %>
    4: <% html_title(l(:plugin_user_preferences_title)) -%>
    5: <div class="plugin_mite_config">
  app/helpers/application_helper.rb:1078:in `stylesheet_link_tag'
  app/helpers/application_helper.rb:1117:in `content_for'
```

**Comment by thomasklein** [comment]
Hi Makkes! Please retry it with a more modern Ruby version as this plugin relies on Ruby >= 1.9 (https://github.com/thomasklein/redmine2mite#requirements)

**Comment by makkes** [comment]
I'm sorry for not being active on this. I'll have to upgrade the distribution of the server for getting Ruby 1.9. I'll close the issue in the meantime and reopen if it still applies.

**Comment by thomasklein** [comment]
ok!
