### ISSUE TITLE
Plugin funktioniert nicht mit Redmine 3.3.1

### ISSUE THREAD

**Issue by Michael-Nussbaumer** [thomasklein/redmine2mite#37]
Ich habe versucht das Plugin auf Redmine 3.3.1 zu installieren. Sobald ich migriert habe funktioniert Redmine nicht mehr.

**General Ruby interpreter information**

```
RUBY_VERSION = 1.9.3
RUBY_PLATFORM = x86_64-linux
RUBY_ENGINE = ruby
RubyGems version = 2.4.3
RubyGems paths = ["/usr/local/rvm/gems/ruby-1.9.3-p551", "/usr/local/rvm/gems/ruby-1.9.3-p551@global"]
```

```
cannot load such file -- active_resource (LoadError)
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'block in require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /data/www/redmine/plugins/redmine2mite/lib/mite-rb.rb:2:in '<top (required)>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'block in require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /data/www/redmine/plugins/redmine2mite/lib/time_entry_patch.rb:2:in '<top (required)>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'block in require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /data/www/redmine/plugins/redmine2mite/init.rb:2:in '<top (required)>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'block in require'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
  /data/www/redmine/lib/redmine/plugin.rb:155:in 'block in load'
  /data/www/redmine/lib/redmine/plugin.rb:146:in 'each'
  /data/www/redmine/lib/redmine/plugin.rb:146:in 'load'
  /data/www/redmine/config/initializers/30-redmine.rb:21:in '<top (required)>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in 'load'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in 'block in load'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in 'load'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in 'block in load_config_initializer'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in 'instrument'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in 'load_config_initializer'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in 'block (2 levels) in <class:Engine>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in 'each'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in 'block in <class:Engine>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in 'instance_exec'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in 'run'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in 'block in run_initializers'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:150:in 'block in tsort_each'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:183:in 'block (2 levels) in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:210:in 'block (2 levels) in each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:219:in 'each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:209:in 'block in each_strongly_connected_component_from'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in 'each'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in 'tsort_each_child'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:203:in 'each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:182:in 'block in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:180:in 'each'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:180:in 'each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tsort.rb:148:in 'tsort_each'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in 'run_initializers'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/application.rb:352:in 'initialize!'
  /data/www/redmine/config/environment.rb:14:in '<top (required)>'
  config.ru:3:in 'require'
  config.ru:3:in 'block in <main>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/builder.rb:55:in 'instance_eval'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.4/lib/rack/builder.rb:55:in 'initialize'
  config.ru:1:in 'new'
  config.ru:1:in '<main>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:110:in 'eval'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:110:in 'preload_app'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:156:in '<module:App>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:30:in '<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.30/src/helper-scripts/rack-preloader.rb:29:in '<main>'
```

**Comment by yolk** [comment]
Konntest du vielleicht versuchen das rubygem `activeresource`zu installieren?

```
gem install activeresource
```

**Comment by yolk** [comment]
Noch besser: Wie [hier](https://www.redmine.org/projects/redmine/wiki/redmineinstall#Additional-dependencies-Gemfilelocal) beschrieben `activeresource` in `Gemfile.local` eintragen.

```
# Gemfile.local
gem 'activeresource'
```

Und dann im redmine-Ordner `bundle install` ausführen. Allerdings keine Garantie, dass redmine2mite mit redmine v3 überhaupt funktioniert.

**Comment by Michael-Nussbaumer** [comment]
Danke für die Antwort, hatte ich auch schon probiert. Beim `rake` kommt dann folgender Fehler:

```
rake aborted!
ArgumentError: The scope body needs to be callable.
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.7.1/lib/active_record/scoping/named.rb:143:in `scope'
/data/www/redmine/plugins/redmine2mite/lib/time_entry_patch.rb:19:in `block in included'
/data/www/redmine/plugins/redmine2mite/lib/time_entry_patch.rb:10:in `class_eval'
/data/www/redmine/plugins/redmine2mite/lib/time_entry_patch.rb:10:in `included'
/data/www/redmine/plugins/redmine2mite/init.rb:15:in `include'
/data/www/redmine/plugins/redmine2mite/init.rb:15:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/data/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by yolk** [comment]
Ja, da scheint einiges mit der aktuellen Version 3 von Redmine bzw. der Version 4 von Rails nicht mehr korrekt zu funktionieren.

@thomasklein: Hast du Muse hier Hand anzulegen?

**Comment by thomasklein** [comment]
Aktuell leider nicht. Bin von Arbeit aus voll mit Projekten und nun auch schon ein wenig raus aus der RoR + Redmine Welt. Ich denke also in naher Zukunft eher nicht. @MichaelNussbaumerGOWEST bin aber natürlich offen für jeglichen Support an der Stelle :)

**Comment by yolk** [comment]
Wärst du denn bereit mit commit-Recht auf der repository zu geben? Dann versuche ich das mal bei Zeiten anzugehen um redmine2mite auf redmine v3 zum laufen zu bekommen.

@MichaelNussbaumerGOWEST: Etwaiige Mithilfe wär sehr willkommen; muss auch grade haushalten ;)

**Comment by Michael-Nussbaumer** [comment]
@yolk: Ich habe eigentlich keine Kenntnisse in RoR, ich habe auf der Suche nach dem passenden Bugtracker zu mite eben Redmine installiert und bin an der Plugininstallation dann gescheitert. Ich denke ich wäre hier nicht wirklich eine Hilfe für dich.
